### ISSUE TITLE
Unable to install 0.2.0 in gradle / Android Studio

### ISSUE THREAD

**Issue by lmick002** [supabase/postgrest-kt#1]
# Bug report

Trying to install this postgrest-kt package via gradle like this:

`   def supabase_version = "0.2.0"
    implementation "io.supabase:postgrest-kt:${supabase_version}"`

Throws an error while building:

`Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find io.supabase:postgrest-kt:0.2.0.
     Required by:
         project :app`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Add 
`    // Supabase
    def supabase_version = "0.2.0"
    implementation "io.supabase:postgrest-kt:${supabase_version}"`

2. Build Project

## Expected behavior

Android Studio builds successfully, and you're able to run/test the postgrest library. 

## System information

MacBook Pro (Retina, 15-inch, Late 2013)
Android Studio 4.2 Beta 5
Build #AI-202.7660.26.42.7141121, built on February 11, 2021
Runtime version: 11.0.8+10-b944.6916264 x86_64
VM: OpenJDK 64-Bit Server VM by N/A
macOS 10.16
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8

## Additional context

Great work thus far! Cant wait to use it.

**Comment by kevcodez** [comment]
Thank you for the bug report! I haven't tested the integration in an Android project yet and will have a look at this!

**Comment by kevcodez** [comment]
It seems like the lib is not fully published on JCenter, thus the dependency cannot be found. I don't have access to JCenter but I messaged @kiwicopple so he can have a look.

Since JCenter is closing within the next 12 months, the plan is to publish to MavenCentral directly, lacking access so far though.

**Comment by lmick002** [comment]
awesome @kevcodez . that makes total sense.

**Comment by kevcodez** [comment]
@lmick002 The library has been linked to JCenter and should not be resolvable as long as you have JCenter as one of your repositories, not sure if that's a default for android, if not, put `jcenter()` in your `repositories` block.

I haven't tested this under Android at all, so there might be additional issues but the dependency at least resolves correctly now.
